# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.srcs/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0.xci
# IP: The module: 'ultrasoon_test_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.srcs/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0.xci
# IP: The module: 'ultrasoon_test_clk_wiz_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/Jochem/GitHub/Fontys/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ultrasoon_test/ip/ultrasoon_test_clk_wiz_0_0/ultrasoon_test_clk_wiz_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ultrasoon_test_clk_wiz_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
