# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints.xdc

# Block Designs: bd/ZYNQ/ZYNQ.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ || ORIG_REF_NAME==ZYNQ} -quiet] -quiet

# IP: bd/ZYNQ/ip/ZYNQ_clk_wiz_0/ZYNQ_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0} -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0/ZYNQ_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0/ZYNQ_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==ZYNQ_clk_wiz_0 || ORIG_REF_NAME==ZYNQ_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ZYNQ/ip/ZYNQ_clk_wiz_0/ZYNQ_clk_wiz_0_ooc.xdc

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong/fontys-pong.gen/sources_1/bd/ZYNQ/ZYNQ_ooc.xdc
