# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_cmodA7.xdc

# Block Designs: bd/CMOD_A7_35T/CMOD_A7_35T.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CMOD_A7_35T || ORIG_REF_NAME==CMOD_A7_35T} -quiet] -quiet

# IP: bd/CMOD_A7_35T/ip/CMOD_A7_35T_clk_wiz_0/CMOD_A7_35T_clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_clk_wiz_0 || ORIG_REF_NAME==CMOD_A7_35T_clk_wiz_0} -quiet] -quiet

# IP: bd/CMOD_A7_35T/ip/CMOD_A7_35T_util_vector_logic_0_0/CMOD_A7_35T_util_vector_logic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_util_vector_logic_0_0 || ORIG_REF_NAME==CMOD_A7_35T_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CMOD_A7_35T/ip/CMOD_A7_35T_util_vector_logic_1_1/CMOD_A7_35T_util_vector_logic_1_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_util_vector_logic_1_1 || ORIG_REF_NAME==CMOD_A7_35T_util_vector_logic_1_1} -quiet] -quiet

# IP: bd/CMOD_A7_35T/ip/CMOD_A7_35T_util_vector_logic_1_2/CMOD_A7_35T_util_vector_logic_1_2.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_util_vector_logic_1_2 || ORIG_REF_NAME==CMOD_A7_35T_util_vector_logic_1_2} -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/CMOD_A7_35T/ip/CMOD_A7_35T_clk_wiz_0/CMOD_A7_35T_clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_clk_wiz_0 || ORIG_REF_NAME==CMOD_A7_35T_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/CMOD_A7_35T/ip/CMOD_A7_35T_clk_wiz_0/CMOD_A7_35T_clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==CMOD_A7_35T_clk_wiz_0 || ORIG_REF_NAME==CMOD_A7_35T_clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/CMOD_A7_35T/ip/CMOD_A7_35T_clk_wiz_0/CMOD_A7_35T_clk_wiz_0_ooc.xdc

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/CMOD_A7_35T/CMOD_A7_35T_ooc.xdc
