set_property SRC_FILE_INFO {cfile:D:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.srcs/constrs_1/new/constraints_cmodA7.xdc rfile:../../../fontys-pong_Artix7.srcs/constrs_1/new/constraints_cmodA7.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A18    IOSTANDARD LVCMOS33 } [get_ports reset];                    #IO_L19N_T3_VREF_16     Sch=btn[0]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN M3     IOSTANDARD LVCMOS33 } [get_ports enable];                   #IO_L8N_T1_AD14N_35     Sch=pio[01]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN L3     IOSTANDARD LVCMOS33 } [get_ports controller_switch];        #IO_L8P_T1_AD14P_35     Sch=pio[02]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A16    IOSTANDARD LVCMOS33 } [get_ports btn_up_l];                 #IO_L12P_T1_MRCC_16     Sch=pio[03]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN K3     IOSTANDARD LVCMOS33 } [get_ports btn_down_l];               #IO_L7N_T1_AD6N_35      Sch=pio[04]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN C15    IOSTANDARD LVCMOS33 } [get_ports btn_up_r];                 #IO_L11P_T1_SRCC_16     Sch=pio[05]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN H1     IOSTANDARD LVCMOS33 } [get_ports btn_down_r];               #IO_L3P_T0_DQS_AD5P_35  Sch=pio[06]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A15    IOSTANDARD LVCMOS33 } [get_ports trigger_l];                #IO_L6N_T0_VREF_16      Sch=pio[07]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN B15    IOSTANDARD LVCMOS33 } [get_ports sensor_l];                 #IO_L11N_T1_SRCC_16     Sch=pio[08]
set_property src_info {type:XDC file:1 line:34 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN A14    IOSTANDARD LVCMOS33 } [get_ports trigger_r];                #IO_L6P_T0_16           Sch=pio[09]
set_property src_info {type:XDC file:1 line:35 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN J3     IOSTANDARD LVCMOS33 } [get_ports sensor_r];                 #IO_L7P_T1_AD6P_35      Sch=pio[10]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V2    IOSTANDARD LVCMOS33 } [get_ports { hdmi_out_hpd[0] }];       #IO_L5P_T0_34           Sch=pio[33]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W3    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_clk_n }];        #IO_L6N_T0_VREF_34      Sch=pio[34]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V3    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_clk_p }];        #IO_L6P_T0_34           Sch=pio[35]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W5    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_p[0] }];    #IO_L12P_T1_MRCC_34     Sch=pio[36]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V4    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_n[0] }];    #IO_L11N_T1_SRCC_34     Sch=pio[37]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U4    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_p[1] }];    #IO_L11P_T1_SRCC_34     Sch=pio[38]
set_property src_info {type:XDC file:1 line:48 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN V5    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_n[1] }];    #IO_L16N_T2_34          Sch=pio[39]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN W4    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_n[2] }];    #IO_L12N_T1_MRCC_34     Sch=pio[40]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict { PACKAGE_PIN U5    IOSTANDARD TMDS_33 }  [get_ports { hdmi_out_data_p[2] }];    #IO_L16P_T2_34          Sch=pio[41]
