# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.srcs/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/blockdesign_rgb2dvi_0_1.xci
# IP: The module: 'blockdesign_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.srcs/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/blockdesign_rgb2dvi_0_1.xci
# IP: The module: 'blockdesign_rgb2dvi_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/_code/Git/Fontys/CSA/CSA2-pong/pong-digitaal/fontys-pong_Artix7/fontys-pong_Artix7.gen/sources_1/bd/blockdesign/ip/blockdesign_rgb2dvi_0_1/src/rgb2dvi_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'blockdesign_rgb2dvi_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
