@echo off
REM ****************************************************************************
REM Vivado (TM) v2023.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Jun 20 15:05:40 +0200 2024
REM SW Build 3865809 on Sun May  7 15:05:29 MDT 2023
REM
REM IP Build 3864474 on Sun May  7 20:36:21 MDT 2023
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim controller_ultrasonic_hcsr04_behav -key {Behavioral:sim_1:Functional:controller_ultrasonic_hcsr04} -tclbatch controller_ultrasonic_hcsr04.tcl -protoinst "protoinst_files/bd_18c5.protoinst" -protoinst "protoinst_files/ultrasoon_test.protoinst" -protoinst "protoinst_files/blockdesign.protoinst" -log simulate.log"
call xsim  controller_ultrasonic_hcsr04_behav -key {Behavioral:sim_1:Functional:controller_ultrasonic_hcsr04} -tclbatch controller_ultrasonic_hcsr04.tcl -protoinst "protoinst_files/bd_18c5.protoinst" -protoinst "protoinst_files/ultrasoon_test.protoinst" -protoinst "protoinst_files/blockdesign.protoinst" -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
